@isTest
//name,oc,responsabke carga,tipo de factura,estado,numero,moneda,importe neto gravado
    private class TestTriggerFactura {
        static testMethod void TestTriggerFactura(){
          //Orden_de_compra__c oc = new Orden_de_compra__c(name ='test');
          //insert oc;
          //Factura__c f = new Factura__c(name = 'test',Responsable_carga__c='test',Tipo_de_factura__c ='A',Estado__c='Real',Numero__c ='1',Moneda__c = 'Dolares',Importe_neto__c=1,Orden_de_compra__c =oc.id );
          //insert f;
          //Factura__c f2 = new Factura__c(name = 'test',Responsable_carga__c='test',Tipo_de_factura__c ='A',Estado__c='Real',Numero__c ='1',Moneda__c = 'Dolares',Importe_neto__c=1,Orden_de_compra__c =oc.id );
          //insert f2;

        }
    }